instrumentation:
  excludes: ['node_modules/**', 'docs/**', 'test/**', 'mochawesome-reports/**', 'karma.conf.js', 'geopackage.js', './index.ts', 'lib/db/sqljsAdapter.js', 'lib/tiles/creator/tileUtilities.js']
  include-all-sources: false
reporting:
  dir: 'docs/coverage'
