name: GH Pages Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build GeoPackage Viewer
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - uses: actions/checkout@v1
    - name: Build gh-pages
      run: npm run gh-pages-build
    - name: Deploy To gh-pages branch
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_branch: gh-pages
        publish_dir: ./docs
